version: 2
updates:
  # npm パッケージの監視
  # サプライチェーン攻撃対策：通常更新は週次チェック
  # セキュリティ更新は自動的に即座に作成されます
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      # 本番依存関係のグループ化（マイナー・パッチのみ）
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      # 開発依存関係のグループ化（マイナー・パッチのみ）
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"

  # GitHub Actionsの監視
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    cooldown:
      default-days: 7
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

